---
jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
      - epel-all
      - fedora-eln
  - job: copr_build
    trigger: commit
    branch: main
    targets:
      - fedora-all
      - epel-all
      - fedora-eln
    owner: "@osci"
    project: mini-tps
